Added classes to show more button and improved captions
mendix/SimpleCheckboxSetSelector pull request #8
Opened 2022-01-18 11:13 UTC by Membad

- Improved the captions of the "Show more" and "Hide" buttons to respectively "Show More" and "Show Less".
- Added a class indicating if the "Show More" or "Show Less" state is currently visible.
- Added file to make sure it's clear what node version is required.

2022-01-19 15:16 UTC, diego-antonelli requested changes
Small change requested. Good PR!

2022-01-19 15:16 UTC, diego-antonelli commented on package-lock.json
> +        "array-uniq": "^1.0.1"
Changes in libraries needs to be undone as  there is not changes in libs

2022-01-19 16:18 UTC, Membad commented on package-lock.json
> +        "array-uniq": "^1.0.1"
Good find. Fixed it!

2022-01-19 16:22 UTC, diego-antonelli approved these changes

2022-01-26 15:56 UTC, leonardomendix approved these changes

2022-01-27 09:18 UTC, merged